[project]
name = "cli-ai-assistant"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Chaman Rawat", email = "chamanrawat.dev@gmail.com" }
]
requires-python = ">=3.14"
dependencies = [
    "openai>=3.3.1",
    "pydantic>=2.13.4",
    "python-dotenv>=1.2.3",
]

[project.scripts]
cli-ai-assistant = "cli_ai_assistant:main"
"assistant.py" = "cli_ai_assistant.assistant:main"
"assistant" = "cli_ai_assistant.assistant:main"

[build-system]
requires = ["uv_build>=0.12.5,<0.13.0"]
build-backend = "uv_build"
